### PR TITLE
Add new 'Move (left | right) within Category' menu options 

### LINKED ISSUE #108: When grouped by category, "Move Left" and "Move Right" changes standard order
To replicate:
1. have more than two categories and more than 2 grade items per category
2. click "Group by Category"
3. open the menu for a grade item  and click "Move Right" (or "Move Left")
4. Page refreshes
5. Grade item has been moved right in non-categorised mode
6. click "Group by Category" again
7. Grade item has not been moved to the right of its category sibling

### PR DESCRIPTION
**Pull request by payten**
Added two new header menu options to reorder within the category sort order.  Only show these menu options when categories are enabled.

Fixes #108.

### CODE REVIEW

**Comment by payten** [comment]
Hm hang on a tick.  Just saw your message on #108 regarding session state.  That might work nicer than having two sets of menu options.  Will close for now and refactor!

**Comment by payten** [comment]
Hi @steveswinsburg, 

I've had a go at adding the state of the categories being enabled to the page state - see `GbSpreadsheetState`.  The `categoriesEnabled` boolean is now changed by the Group by Categories button and this value is stored on this model.  Now when Move Left | Right is clicked, this state model is queried to determine if sort order should be applied within the category or not.

Also, now that  categoriesEnabled is retained on the state, the Javascript will re-enable categories upon refresh if the button is checked/`on`.

Thanks,
Payten

**Comment by steveswinsburg** [comment]
Oh the merge is broken :(

**Comment by steveswinsburg** [comment]
Question though, where is the state model persisted into/retrieved from the session so it lives across requests? I have that bit if you want, when I merge I'll commit it back in.

**Comment by steveswinsburg** [comment]
Ok that session state saving is in, I skyped you some notes :)

**Comment by payten** [comment]
Hi @steveswinsburg.  I've rebased and refactored to make use of the session state model `GradebookUiSettings.java`.  Thanks for that.

I did notice a NPE in the sorting code where it expected an assignmentSortOrder when there wasn't one. The patch below saved the day:

```
 -               if(settings != null) {
 +               if(settings != null && settings.getAssignmentSortOrder() != null) {
                         title.add(new AttributeModifier("class", "gb-sort-" + settings.getAssignmentSortOrder().getDirection().toString().toLowerCase()));
                 }
```

I did notice there's a few places were we repeat this `settings == null` check.  Perhaps we could refactor to lazy initialize?

**Comment by payten** [comment]
On a roll.. so added `assignmentVisibility` to the session state to persist whether grade item columns have been hidden.

**Comment by steveswinsburg** [comment]
Ok nice one. Yeah there's probably a few things we can do with that session storage. I toyed with the idea of getUiSettings() always returning an instance but then its being created even for a check if it exists. Tiny object, null check is probably ok, or we can maintain a flag but then it needs to be passed around and looked up. Trade off somewhere lol.

**Pull request merged**
