### PR TITLE
Feature/ta permissions

### PR DESCRIPTION
**Pull request by steveswinsburg**
Added in the group and user checking if user is a TA. Tas should now only see users they have been given access to.

Also added in error page. Error will be thrown if user is on a page, then permissions are reduced and then click on a student to view their grades that they no longer has access to view.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Hey payten, could you run this up and test? I still need to filter the categories but would be good to get early feedback. You'll need to use the old gradebook permissions page to set the perms. Once this is nailed down I'll get the GBNG page in.

You'll also need current trunk as there is another API change.

**Comment by payten** [comment]
Hi @steveswinsburg. I only had a chance to take a quick look today. 

When there are no rules, the TA sees nothing: 
152_no_rules

The filtering by section seems to be working nicely.  However when I added a "grade" rule for a certain section the cells were not editable: 152_grade_section.  (The scores are still editable when accessed by an Instructor).

And lastly I came across an NPE when a rule contained a category (but perhaps I'm jumping the gun on testing that!): 152_grade_category_section

I'll set aside some Gradebook time tomorrow so can work through testing these rules in more detail.

**Comment by steveswinsburg** [comment]
Hi Payten,

When a TA has no rules, they see nothing, that is consistent with the old
gradebook, however the old GB still shows the gradebook items, just no
students when you drill in. Because our rendering is student based, not
assignment based like the old GB, we might need to do something different
there.

The editable one is weird, there shouldn't be a change there, I haven't
touched that bit yet, just the user/group filtering.

Categories will be sorted soon, they haven't been filtered yet. Though that
RuntimeException should have been caught by the new error page I also
added, hmm.

cheers,
Steve

**Comment by steveswinsburg** [comment]
I've gone ahead and stuck this into master and we can work out the rest of the mods from there.

**Comment by payten** [comment]
Hi @steveswinsburg,

Just running through a few scenarios:
- No rules:  I guess I imagined not being able to see any students and no grade items.  Also, should we disable or hide all the Edit, Move and Set Score actions for TAs?
- "View" on category and all sections: All students display and grade items are limited to the category I selected and are read only. However, all the category totals columns are visible which causes a javascript error and Group by Categories doesn't work.
- "Grade" on category and all sections: Javascript described above breaks editing.  When catching and ignoring the JS exception, everything seems to work otherwise!
- "Grade" on category and a group: Works well.
- "View" on category and all sections + "Grade" on same category and a group: Cells for all students are editable but hits "Something went wrong" page when trying to edit a student not in the "Grade" group.  Editing scores for students in the group worked nicely.
- "View" on category and all sections + "Grade" on a different category and a group: "Something went wrong".

**Comment by steveswinsburg** [comment]
Hi @payten:

_No rules: I guess I imagined not being able to see any students and no grade items. Also, should we disable or hide all the Edit, Move and Set Score actions for TAs?_

Yeah I haven't done any front end mods at all, those will be hidden. 

_"View" on category and all sections: All students display and grade items are limited to the category I selected and are read only. However, all the category totals columns are visible which causes a javascript error and Group by Categories doesn't work._

The readonly bit concerns me, no UI mods made, so that could be a javascript bug?

_"Grade" on category and all sections: Javascript described above breaks editing. When catching and ignoring the JS exception, everything seems to work otherwise!_

Yeah sounds like an issue we need to look at. When rendering the cells I was going to put some logic in there if TA then to run some checks.

_"Grade" on category and a group: Works well._
:+1: 

_"View" on category and all sections + "Grade" on same category and a group: Cells for all students are editable but hits "Something went wrong" page when trying to edit a student not in the "Grade" group. Editing scores for students in the group worked nicely._

Ok yep I haven't done the same checks on the actual grading yet, just the view.

_"View" on category and all sections + "Grade" on a different category and a group: "Something went wrong"._

Hmm, need to check this out, can you grab the logs?

**Pull request merged**
