### PR TITLE
Setup column header flags as Bootstrap popovers…

### PR DESCRIPTION
**Pull request by payten**
… and ensure they can be focused and don't get caught up in the drag and drop event cycle.

Delivers enhancement raised in 10/1/2015 team call: "Icons/Tooltips feel like they should be clickable...maybe popovers like the rest of the interface?"

### CODE REVIEW

**Comment by payten** [comment]
I've also ensured that icon flags in the instructor and student grade drilldown templates are popover-ified too.

**Comment by kyleblythe** [comment]
Hey @payten ,

This is a very minor change, but thought this might be the best issue to associate it with.

Can we modify the text for these popover images to include "Item" at the beginning?

i.e., "Item not included in course grade calculation" and "Item not released to students"

Thanks!

**Comment by payten** [comment]
I've updated the following to use 'Gradebook Item' consistently (most were 'Gradebook Item' rather than just 'Item'). Is that ok?

```
label.gradeitem.externalAppPrefix=Gradebook Item coming from
label.gradeitem.released=Gradebook Item has been released and is visible to students.
label.gradeitem.notreleased=Gradebook Item not released to students.
label.gradeitem.counted=Gradebook Item is included in the course grade calculation.
label.gradeitem.notcounted=Gradebook Item not included in course grade calculation.
label.gradeitem.extracredit=This is an Extra Credit Gradebook Item
label.gradeitem.extracreditcategory=This is an Extra Credit Category
```

**Comment by steveswinsburg** [comment]
Hey @kyleblythe, quick check on the above text and then I'll merge this in (or you can, if feeling adventurous and the button is still green :)

**Comment by steveswinsburg** [comment]
Oh actually @payten, I think we need another push for this?

**Pull request merged**
