### PR TITLE
Add new JS and CSS resources for the GradebookPage page

### PR DESCRIPTION
**Pull request by payten**
Introduce javascript to handle the dropdown menus and basic CSS to style the table/cells.

I've rebased with your commits from last week, so hopefully it's looking ok.

I noticed that the wicket grid is swallowing javascript click events and not propagating them up to the container. Are we able to customise that javascript?  This may affect performance as we will need to bind events to the individual elements rather that catching the event higher up the DOM - I hit this when binding the click event to the menu toggles.

Also, after clicking on the row, further clicks on the menu toggle event are seemingly suppressed. Another grid side-effect?

### CODE REVIEW

**Comment by steveswinsburg** [comment]
Hey, thanks for this Payten. I'll have to look into the JS eventing that's going on. 

We might actually be able to use the standard wicket links for the actual links but use this for the styling.

I still need to port across the editable grid code so that a click on the score triggers the edit, that was lost with the move to the panel cells since what we have is more complex than just a normal cell, so we can likely address that with the port.

**Comment by payten** [comment]
Hm I didn't realise that Bootstrap was included in Sakai!  I just noticed https://jira.sakaiproject.org/browse/SAK-29017.  I guess this means we're ok to use Bootstrap components, including the menus?

**Comment by steveswinsburg** [comment]
Yeah we should be. I added the wicket-bootstrap component as a dependency, but using native bootstrap would be fine too. Did you want me to pull this PR in anyway?

**Comment by payten** [comment]
Perhaps hold off on it - by just including Bootstrap it will do the dropdown menus for us, so I can remove all my custom JS. 

Does the wicket-bootstrap component load the resources for us? Or should we be including the CSS/JS from the Sakai versions/paths?

**Comment by steveswinsburg** [comment]
I think we are better off including the Sakai versions so we don't run into inconsistencies. Lets try that first. The wicket bootstrap is in there but commented out so we can always try that quickly if need be.

**Comment by payten** [comment]
Hi @steveswinsburg.  I've included bootstrap and now allow it to do its thing with the dropdown menus.  For the bootstrap menus to work within the wicket-grid I had to force overflow:visible on all the parent elements so the bootstrap menu dropdown displays.  Because of this, I'm not completely sold on the use of bootstrap... it may end up further conflicting with the wicket css and causing us headaches.  Let me know what you'd prefer and we can merge this PR as is or roll it back to the previous commit that uses the bespoke javascript/css.

**Comment by steveswinsburg** [comment]
Scratch that, my bootstrap was out of date in Sakai master. Looks great @payten. Just want to double check we are all good to use wicket:ids in the links in the menu?

**Pull request merged**
